source 'https://github.com/CocoaPods/Specs.git'
xcodeproj 'IntripperSampleApp.xcodeproj'
# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.1"

target "IntripperSampleApp" do
    pod 'GoogleMaps'
    pod "AFNetworking", "~> 2.0"
end

